### ISSUE TITLE
TransactionEventService Implementation

### ISSUE THREAD

**Issue by guga2002** [guga2002/RGBA.Optio.UI#14]
გაუკეთეთ იმპლემენტაცია TransactionEventService-ს  ,ეს კლასი შემდეგ ხელმისაწვდომი იქნება ადმინისთვის , რათა დაამატოს  ტრანზაქციის ტიპები ან ვალუტის კურსი , და ასე შემდეგ.

**Comment by RaisaBadal** [comment]
გურამ,

**_public async Task<bool> AddAsync(ValuteModel entity)_** ამ მეთოდთან დაკავშირებით მაქვს გარკვეული კითხვები, როცა გეცლება მოკლე ქოლი დავნიშნოთ
