### ISSUE TITLE
Attributes in Model Classess

### ISSUE THREAD

**Issue by guga2002** [guga2002/RGBA.Optio.UI#18]
დაამატე ვალიდაციები მოდელ კლასში , შეგიძლია შექმნა  ქასთამ ვალიდაციებიც , ამისათვის დაამატე ვალიდაციის ფოლდერში ახალი ფოლდერი სადაც შექმნი , ვალიდაციის კლასებს. გამოიყენე ველებთან , Required  სადაც  ჩათვლი საჭიროდ.

**Comment by RaisaBadal** [comment]
გამარჯობა გურამ,

ამ საკითხს სანამ დაიწყებ მოკლე ქოლი დავნიშნოთ, რაღაც დეტალებია გასავლელი.

**Comment by guga2002** [comment]
რაისა მოვრჩი ამ დავალებას ,  გადახედე როცა მოახერხებ, ნებისმიერი კითხვის შემთხვევაში გავიაროთ დეტალები.
