### ISSUE TITLE
Category and TypeOfTransaction refactoring

### ISSUE THREAD

**Issue by RaisaBadal** [guga2002/RGBA.Optio.UI#33]
გაასწორეთ კავშირი ამ ორი ცხრილის, კერძოდ დააკავშირეთ კატეგორია მთავარ ტრანზაქციასთან, ხოლო ტიპი კატეგორიასთან.

**Comment by guga2002** [comment]
რაისა, შევასრულე დავალება , კითხვების შემთხვევაში ერთად გავიაროთ დეტალები.
