### ISSUE TITLE
TransactionRelatedService იმპლემენტაცია

### ISSUE THREAD

**Issue by RaisaBadal** [guga2002/RGBA.Optio.UI#45]
გაუკეთეთ იმპლემენტაცია მოცემულ სერვისს კლასს, ფუნქციები გამზადებულია ჩამოწერილია მხოლოდ იმპლემენტაციაა დარჩენილი

**Comment by guga2002** [comment]
შევასრულე ეს დავალება . მერე  ბოლოს გავტესტოთ.
